// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: examples/vesting/v1/vesting.proto

package v1

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Init struct {
	Beneficiary string         `protobuf:"bytes,1,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	StartTime   *time.Time     `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time,omitempty"`
	Duration    *time.Duration `protobuf:"bytes,3,opt,name=duration,proto3,stdduration" json:"duration,omitempty"`
}

func (m *Init) Reset()         { *m = Init{} }
func (m *Init) String() string { return proto.CompactTextString(m) }
func (*Init) ProtoMessage()    {}
func (*Init) Descriptor() ([]byte, []int) {
	return fileDescriptor_13390107e5744991, []int{0}
}
func (m *Init) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Init) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Init.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Init) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Init.Merge(m, src)
}
func (m *Init) XXX_Size() int {
	return m.Size()
}
func (m *Init) XXX_DiscardUnknown() {
	xxx_messageInfo_Init.DiscardUnknown(m)
}

var xxx_messageInfo_Init proto.InternalMessageInfo

func (m *Init) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

func (m *Init) GetStartTime() *time.Time {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Init) GetDuration() *time.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type MsgWithdrawUnlockedCoins struct {
}

func (m *MsgWithdrawUnlockedCoins) Reset()         { *m = MsgWithdrawUnlockedCoins{} }
func (m *MsgWithdrawUnlockedCoins) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawUnlockedCoins) ProtoMessage()    {}
func (*MsgWithdrawUnlockedCoins) Descriptor() ([]byte, []int) {
	return fileDescriptor_13390107e5744991, []int{1}
}
func (m *MsgWithdrawUnlockedCoins) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawUnlockedCoins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawUnlockedCoins.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawUnlockedCoins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawUnlockedCoins.Merge(m, src)
}
func (m *MsgWithdrawUnlockedCoins) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawUnlockedCoins) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawUnlockedCoins.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawUnlockedCoins proto.InternalMessageInfo

type QueryVestingStatusRequest struct {
}

func (m *QueryVestingStatusRequest) Reset()         { *m = QueryVestingStatusRequest{} }
func (m *QueryVestingStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVestingStatusRequest) ProtoMessage()    {}
func (*QueryVestingStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13390107e5744991, []int{2}
}
func (m *QueryVestingStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVestingStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVestingStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVestingStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVestingStatusRequest.Merge(m, src)
}
func (m *QueryVestingStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVestingStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVestingStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVestingStatusRequest proto.InternalMessageInfo

type QueryVestingStatusResponse struct {
	UnlockedAmount     github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=unlocked_amount,json=unlockedAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"unlocked_amount"`
	WithdrawableAmount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=withdrawable_amount,json=withdrawableAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"withdrawable_amount"`
}

func (m *QueryVestingStatusResponse) Reset()         { *m = QueryVestingStatusResponse{} }
func (m *QueryVestingStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVestingStatusResponse) ProtoMessage()    {}
func (*QueryVestingStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13390107e5744991, []int{3}
}
func (m *QueryVestingStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVestingStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVestingStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVestingStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVestingStatusResponse.Merge(m, src)
}
func (m *QueryVestingStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVestingStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVestingStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVestingStatusResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Init)(nil), "examples.vesting.v1.Init")
	proto.RegisterType((*MsgWithdrawUnlockedCoins)(nil), "examples.vesting.v1.MsgWithdrawUnlockedCoins")
	proto.RegisterType((*QueryVestingStatusRequest)(nil), "examples.vesting.v1.QueryVestingStatusRequest")
	proto.RegisterType((*QueryVestingStatusResponse)(nil), "examples.vesting.v1.QueryVestingStatusResponse")
}

func init() { proto.RegisterFile("examples/vesting/v1/vesting.proto", fileDescriptor_13390107e5744991) }

var fileDescriptor_13390107e5744991 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x3d, 0x8f, 0xd3, 0x30,
	0x18, 0x8e, 0x8f, 0x0a, 0x71, 0x3e, 0x09, 0xa4, 0x1c, 0x43, 0x2e, 0xa0, 0xa4, 0x64, 0x40, 0xb7,
	0x60, 0xeb, 0x40, 0x62, 0x61, 0x40, 0x04, 0x96, 0x1b, 0x18, 0x08, 0x1f, 0x27, 0xb1, 0x54, 0x4e,
	0xe2, 0xcb, 0x59, 0x97, 0xd8, 0x21, 0x7e, 0xdd, 0xd2, 0x7f, 0xd1, 0x91, 0x5f, 0xc0, 0x6f, 0xe9,
	0xd8, 0x09, 0x21, 0x86, 0x82, 0xda, 0x3f, 0x82, 0xf2, 0x61, 0x54, 0x41, 0x27, 0xa6, 0xbc, 0x7a,
	0xde, 0xe7, 0x2b, 0xaf, 0x8c, 0x1f, 0xf0, 0xcf, 0xac, 0xaa, 0x4b, 0xae, 0xe9, 0x94, 0x6b, 0x10,
	0xb2, 0xa0, 0xd3, 0x33, 0x3b, 0x92, 0xba, 0x51, 0xa0, 0xdc, 0x63, 0x4b, 0x21, 0x16, 0x9f, 0x9e,
	0xf9, 0x61, 0xa1, 0x54, 0x51, 0x72, 0xda, 0x51, 0x52, 0x73, 0x49, 0x41, 0x54, 0x5c, 0x03, 0xab,
	0xea, 0x5e, 0xe5, 0x07, 0x7f, 0x13, 0x72, 0xd3, 0x30, 0x10, 0x4a, 0x0e, 0xfb, 0xbb, 0x85, 0x2a,
	0x54, 0x37, 0xd2, 0x76, 0xea, 0xd1, 0xe8, 0x2b, 0xc2, 0xa3, 0x73, 0x29, 0xc0, 0x1d, 0xe3, 0xa3,
	0x94, 0x4b, 0x7e, 0x29, 0x32, 0xc1, 0x9a, 0xb9, 0x87, 0xc6, 0xe8, 0xf4, 0x30, 0xd9, 0x85, 0xdc,
	0xe7, 0x18, 0x6b, 0x60, 0x0d, 0x4c, 0xda, 0x64, 0xef, 0x60, 0x8c, 0x4e, 0x8f, 0x1e, 0xfb, 0xa4,
	0x4f, 0x25, 0x36, 0x95, 0xbc, 0xb3, 0xb5, 0xe2, 0xd1, 0xe2, 0x67, 0x88, 0x92, 0xc3, 0x4e, 0xd3,
	0xa2, 0xee, 0x33, 0x7c, 0xcb, 0x76, 0xf2, 0x6e, 0x74, 0xf2, 0x93, 0x7f, 0xe4, 0xaf, 0x06, 0x42,
	0x3c, 0xfa, 0xd2, 0xaa, 0xff, 0x08, 0x22, 0x1f, 0x7b, 0xaf, 0x75, 0x71, 0x21, 0xe0, 0x2a, 0x6f,
	0xd8, 0xec, 0xbd, 0x2c, 0x55, 0x76, 0xcd, 0xf3, 0x97, 0x4a, 0x48, 0x1d, 0xdd, 0xc3, 0x27, 0x6f,
	0x0c, 0x6f, 0xe6, 0x1f, 0xfa, 0x73, 0xbd, 0x05, 0x06, 0x46, 0x27, 0xfc, 0x93, 0xe1, 0x1a, 0xa2,
	0x6f, 0x08, 0xfb, 0xfb, 0xb6, 0xba, 0x56, 0x52, 0x73, 0xf7, 0x02, 0xdf, 0x31, 0x83, 0xd9, 0x84,
	0x55, 0xca, 0x48, 0xe8, 0xff, 0x3d, 0x26, 0xcb, 0x75, 0xe8, 0xfc, 0x58, 0x87, 0x0f, 0x0b, 0x01,
	0x57, 0x26, 0x25, 0x99, 0xaa, 0x68, 0xa6, 0x74, 0xa5, 0xf4, 0xf0, 0x79, 0xa4, 0xf3, 0x6b, 0x0a,
	0xf3, 0x9a, 0x6b, 0x72, 0x2e, 0x21, 0xb9, 0x6d, 0x6d, 0x5e, 0x74, 0x2e, 0xee, 0x04, 0x1f, 0xcf,
	0x86, 0xb6, 0x2c, 0x2d, 0xb9, 0x35, 0x3f, 0xf8, 0x2f, 0x73, 0x77, 0xd7, 0xaa, 0x0f, 0x88, 0x9f,
	0x2e, 0x37, 0x01, 0x5a, 0x6d, 0x02, 0xf4, 0x6b, 0x13, 0xa0, 0xc5, 0x36, 0x70, 0x56, 0xdb, 0xc0,
	0xf9, 0xbe, 0x0d, 0x9c, 0x8f, 0xf7, 0x59, 0x96, 0xb5, 0x14, 0x4d, 0xf7, 0x3c, 0xb6, 0xf4, 0x66,
	0x77, 0xec, 0x27, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x76, 0x62, 0xd5, 0xed, 0x8a, 0x02, 0x00,
	0x00,
}

func (m *Init) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Init) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Init) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Duration != nil {
		n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(*m.Duration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(*m.Duration):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintVesting(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x1a
	}
	if m.StartTime != nil {
		n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.StartTime):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintVesting(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Beneficiary) > 0 {
		i -= len(m.Beneficiary)
		copy(dAtA[i:], m.Beneficiary)
		i = encodeVarintVesting(dAtA, i, uint64(len(m.Beneficiary)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawUnlockedCoins) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawUnlockedCoins) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawUnlockedCoins) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryVestingStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVestingStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVestingStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryVestingStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVestingStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVestingStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.WithdrawableAmount.Size()
		i -= size
		if _, err := m.WithdrawableAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVesting(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.UnlockedAmount.Size()
		i -= size
		if _, err := m.UnlockedAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVesting(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintVesting(dAtA []byte, offset int, v uint64) int {
	offset -= sovVesting(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Init) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Beneficiary)
	if l > 0 {
		n += 1 + l + sovVesting(uint64(l))
	}
	if m.StartTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.StartTime)
		n += 1 + l + sovVesting(uint64(l))
	}
	if m.Duration != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdDuration(*m.Duration)
		n += 1 + l + sovVesting(uint64(l))
	}
	return n
}

func (m *MsgWithdrawUnlockedCoins) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryVestingStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryVestingStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.UnlockedAmount.Size()
	n += 1 + l + sovVesting(uint64(l))
	l = m.WithdrawableAmount.Size()
	n += 1 + l + sovVesting(uint64(l))
	return n
}

func sovVesting(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVesting(x uint64) (n int) {
	return sovVesting(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Init) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVesting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Init: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Init: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beneficiary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVesting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Beneficiary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVesting
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StartTime == nil {
				m.StartTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVesting
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Duration == nil {
				m.Duration = new(time.Duration)
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(m.Duration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVesting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVesting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawUnlockedCoins) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVesting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawUnlockedCoins: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawUnlockedCoins: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipVesting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVesting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVestingStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVesting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVestingStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVestingStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipVesting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVesting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVestingStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVesting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVestingStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVestingStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockedAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVesting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnlockedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawableAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVesting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WithdrawableAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVesting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVesting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVesting(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVesting
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVesting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVesting
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVesting
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVesting
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVesting        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVesting          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVesting = fmt.Errorf("proto: unexpected end of group")
)
