// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: accounts/authn/tx.proto

package types

import (
	types "accounts/x/accounts/types"
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateAuthenticatedAccount struct {
	Credential []byte           `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	DeployMsg  *types.MsgDeploy `protobuf:"bytes,2,opt,name=deploy_msg,json=deployMsg,proto3" json:"deploy_msg,omitempty"`
}

func (m *MsgCreateAuthenticatedAccount) Reset()         { *m = MsgCreateAuthenticatedAccount{} }
func (m *MsgCreateAuthenticatedAccount) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAuthenticatedAccount) ProtoMessage()    {}
func (*MsgCreateAuthenticatedAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_037194ada42e49c5, []int{0}
}
func (m *MsgCreateAuthenticatedAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAuthenticatedAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAuthenticatedAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAuthenticatedAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAuthenticatedAccount.Merge(m, src)
}
func (m *MsgCreateAuthenticatedAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAuthenticatedAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAuthenticatedAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAuthenticatedAccount proto.InternalMessageInfo

func (m *MsgCreateAuthenticatedAccount) GetCredential() []byte {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (m *MsgCreateAuthenticatedAccount) GetDeployMsg() *types.MsgDeploy {
	if m != nil {
		return m.DeployMsg
	}
	return nil
}

type MsgCreateAuthenticatedAccountResponse struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateAuthenticatedAccountResponse) Reset()         { *m = MsgCreateAuthenticatedAccountResponse{} }
func (m *MsgCreateAuthenticatedAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAuthenticatedAccountResponse) ProtoMessage()    {}
func (*MsgCreateAuthenticatedAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_037194ada42e49c5, []int{1}
}
func (m *MsgCreateAuthenticatedAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAuthenticatedAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAuthenticatedAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAuthenticatedAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAuthenticatedAccountResponse.Merge(m, src)
}
func (m *MsgCreateAuthenticatedAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAuthenticatedAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAuthenticatedAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAuthenticatedAccountResponse proto.InternalMessageInfo

func (m *MsgCreateAuthenticatedAccountResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgCreateAuthenticatedAccountResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateCredentials struct {
	Sender   string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Kind     string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	NewAuthn []byte `protobuf:"bytes,3,opt,name=new_authn,json=newAuthn,proto3" json:"new_authn,omitempty"`
}

func (m *MsgUpdateCredentials) Reset()         { *m = MsgUpdateCredentials{} }
func (m *MsgUpdateCredentials) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCredentials) ProtoMessage()    {}
func (*MsgUpdateCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_037194ada42e49c5, []int{2}
}
func (m *MsgUpdateCredentials) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCredentials.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCredentials.Merge(m, src)
}
func (m *MsgUpdateCredentials) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCredentials proto.InternalMessageInfo

func (m *MsgUpdateCredentials) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgUpdateCredentials) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *MsgUpdateCredentials) GetNewAuthn() []byte {
	if m != nil {
		return m.NewAuthn
	}
	return nil
}

type MsgUpdateCredentialsResponse struct {
}

func (m *MsgUpdateCredentialsResponse) Reset()         { *m = MsgUpdateCredentialsResponse{} }
func (m *MsgUpdateCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCredentialsResponse) ProtoMessage()    {}
func (*MsgUpdateCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_037194ada42e49c5, []int{3}
}
func (m *MsgUpdateCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCredentialsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCredentialsResponse.Merge(m, src)
}
func (m *MsgUpdateCredentialsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCredentialsResponse proto.InternalMessageInfo

type MsgDeleteCredentials struct {
}

func (m *MsgDeleteCredentials) Reset()         { *m = MsgDeleteCredentials{} }
func (m *MsgDeleteCredentials) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteCredentials) ProtoMessage()    {}
func (*MsgDeleteCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_037194ada42e49c5, []int{4}
}
func (m *MsgDeleteCredentials) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteCredentials.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteCredentials.Merge(m, src)
}
func (m *MsgDeleteCredentials) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteCredentials proto.InternalMessageInfo

type MsgDeleteCredentialsResponse struct {
}

func (m *MsgDeleteCredentialsResponse) Reset()         { *m = MsgDeleteCredentialsResponse{} }
func (m *MsgDeleteCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteCredentialsResponse) ProtoMessage()    {}
func (*MsgDeleteCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_037194ada42e49c5, []int{5}
}
func (m *MsgDeleteCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteCredentialsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteCredentialsResponse.Merge(m, src)
}
func (m *MsgDeleteCredentialsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteCredentialsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateAuthenticatedAccount)(nil), "accounts.authn.MsgCreateAuthenticatedAccount")
	proto.RegisterType((*MsgCreateAuthenticatedAccountResponse)(nil), "accounts.authn.MsgCreateAuthenticatedAccountResponse")
	proto.RegisterType((*MsgUpdateCredentials)(nil), "accounts.authn.MsgUpdateCredentials")
	proto.RegisterType((*MsgUpdateCredentialsResponse)(nil), "accounts.authn.MsgUpdateCredentialsResponse")
	proto.RegisterType((*MsgDeleteCredentials)(nil), "accounts.authn.MsgDeleteCredentials")
	proto.RegisterType((*MsgDeleteCredentialsResponse)(nil), "accounts.authn.MsgDeleteCredentialsResponse")
}

func init() { proto.RegisterFile("accounts/authn/tx.proto", fileDescriptor_037194ada42e49c5) }

var fileDescriptor_037194ada42e49c5 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xed, 0xb4, 0x2a, 0x64, 0x40, 0x95, 0xba, 0xaa, 0x42, 0x64, 0xca, 0xaa, 0xb2, 0x40,
	0xea, 0x01, 0x6c, 0x5a, 0xc4, 0x89, 0x53, 0x69, 0xaf, 0x3e, 0x60, 0x89, 0x0b, 0x97, 0x68, 0xe3,
	0x1d, 0x6d, 0x2d, 0xd2, 0x5d, 0xcb, 0xb3, 0xa1, 0xad, 0xc4, 0x91, 0x07, 0xe0, 0xb1, 0x38, 0xf6,
	0x88, 0x38, 0xa1, 0xe4, 0x45, 0x50, 0xd6, 0xde, 0xb4, 0x95, 0xa3, 0x28, 0xdc, 0x66, 0x67, 0xbe,
	0x9d, 0xff, 0xdf, 0xb1, 0x07, 0x9e, 0x89, 0xa2, 0x30, 0x53, 0x6d, 0x29, 0x15, 0x53, 0x7b, 0xa1,
	0x53, 0x7b, 0x9d, 0x54, 0xb5, 0xb1, 0x86, 0xed, 0xfa, 0x42, 0xe2, 0x0a, 0x11, 0x2f, 0x0c, 0x5d,
	0x1a, 0x4a, 0xc7, 0x82, 0x30, 0xfd, 0x76, 0x3c, 0x46, 0x2b, 0x8e, 0xd3, 0xc2, 0x94, 0xba, 0xe1,
	0xa3, 0x7d, 0x65, 0x94, 0x71, 0x61, 0xba, 0x88, 0xda, 0x6c, 0x74, 0xd7, 0xde, 0x07, 0x5e, 0x21,
	0xfe, 0x0e, 0x2f, 0x32, 0x52, 0x67, 0x35, 0x0a, 0x8b, 0xa7, 0x53, 0x7b, 0x81, 0xda, 0x96, 0x85,
	0xb0, 0x28, 0x4f, 0x1b, 0x94, 0x71, 0x80, 0xa2, 0x46, 0xb9, 0xc8, 0x8b, 0xc9, 0x30, 0x3c, 0x0c,
	0x8f, 0x9e, 0xe6, 0xf7, 0x32, 0xec, 0x03, 0x80, 0xc4, 0x6a, 0x62, 0x6e, 0x46, 0x97, 0xa4, 0x86,
	0xbd, 0xc3, 0xf0, 0xe8, 0xc9, 0xc9, 0x41, 0x72, 0xe7, 0xdb, 0x07, 0x19, 0xa9, 0x73, 0xc7, 0xe5,
	0xfd, 0x86, 0xcf, 0x48, 0xc5, 0x9f, 0xe0, 0xd5, 0x5a, 0xf5, 0x1c, 0xa9, 0x32, 0x9a, 0x90, 0x0d,
	0xe1, 0x91, 0x90, 0xb2, 0x46, 0x22, 0x67, 0xa1, 0x9f, 0xfb, 0x23, 0xdb, 0x85, 0x5e, 0x29, 0x9d,
	0xee, 0x76, 0xde, 0x2b, 0x65, 0x3c, 0x82, 0xfd, 0x8c, 0xd4, 0xe7, 0x4a, 0x0a, 0x8b, 0x67, 0x4b,
	0x9b, 0xc4, 0x06, 0xb0, 0x43, 0xa8, 0x25, 0xd6, 0x6d, 0x83, 0xf6, 0xc4, 0x18, 0x6c, 0x7f, 0x2d,
	0x75, 0xd3, 0xa1, 0x9f, 0xbb, 0x98, 0x3d, 0x87, 0xbe, 0xc6, 0xab, 0x91, 0x9b, 0xf9, 0x70, 0xcb,
	0x3d, 0xf9, 0xb1, 0xc6, 0xab, 0x85, 0x43, 0x1d, 0x73, 0x38, 0x58, 0x25, 0xe0, 0xad, 0xc6, 0x03,
	0x67, 0xe0, 0x1c, 0x27, 0xf8, 0xa0, 0xde, 0xde, 0xeb, 0xe4, 0xfd, 0xbd, 0x93, 0x3f, 0x3d, 0xd8,
	0xca, 0x48, 0xb1, 0x1f, 0x21, 0x44, 0x6b, 0xbe, 0xc7, 0x9b, 0xe4, 0xe1, 0x3f, 0x91, 0xac, 0x1d,
	0x60, 0xf4, 0xfe, 0xbf, 0xf0, 0xe5, 0x23, 0x02, 0x56, 0xc2, 0x5e, 0x77, 0x88, 0x2f, 0x57, 0x74,
	0xeb, 0x50, 0xd1, 0xeb, 0x4d, 0xa8, 0x7b, 0x52, 0x02, 0xf6, 0x3a, 0x63, 0x59, 0x29, 0xd5, 0xa1,
	0xa2, 0x8d, 0xa8, 0x38, 0xf8, 0xf8, 0xf6, 0xd7, 0x8c, 0x87, 0xb7, 0x33, 0x1e, 0xfe, 0x9d, 0xf1,
	0xf0, 0xe7, 0x9c, 0x07, 0xb7, 0x73, 0x1e, 0xfc, 0x9e, 0xf3, 0xe0, 0xcb, 0x60, 0xb9, 0x13, 0xd7,
	0x7e, 0xfb, 0x6e, 0x2a, 0xa4, 0xf1, 0x8e, 0xdb, 0x8f, 0x77, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xb5, 0x8c, 0x71, 0x3f, 0x9c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateAuthenticatedAccount(ctx context.Context, in *MsgCreateAuthenticatedAccount, opts ...grpc.CallOption) (*MsgCreateAuthenticatedAccountResponse, error)
	UpdateCredentials(ctx context.Context, in *MsgUpdateCredentials, opts ...grpc.CallOption) (*MsgUpdateCredentialsResponse, error)
	DeleteCredentials(ctx context.Context, in *MsgDeleteCredentials, opts ...grpc.CallOption) (*MsgDeleteCredentials, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateAuthenticatedAccount(ctx context.Context, in *MsgCreateAuthenticatedAccount, opts ...grpc.CallOption) (*MsgCreateAuthenticatedAccountResponse, error) {
	out := new(MsgCreateAuthenticatedAccountResponse)
	err := c.cc.Invoke(ctx, "/accounts.authn.Msg/CreateAuthenticatedAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCredentials(ctx context.Context, in *MsgUpdateCredentials, opts ...grpc.CallOption) (*MsgUpdateCredentialsResponse, error) {
	out := new(MsgUpdateCredentialsResponse)
	err := c.cc.Invoke(ctx, "/accounts.authn.Msg/UpdateCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteCredentials(ctx context.Context, in *MsgDeleteCredentials, opts ...grpc.CallOption) (*MsgDeleteCredentials, error) {
	out := new(MsgDeleteCredentials)
	err := c.cc.Invoke(ctx, "/accounts.authn.Msg/DeleteCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateAuthenticatedAccount(context.Context, *MsgCreateAuthenticatedAccount) (*MsgCreateAuthenticatedAccountResponse, error)
	UpdateCredentials(context.Context, *MsgUpdateCredentials) (*MsgUpdateCredentialsResponse, error)
	DeleteCredentials(context.Context, *MsgDeleteCredentials) (*MsgDeleteCredentials, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateAuthenticatedAccount(ctx context.Context, req *MsgCreateAuthenticatedAccount) (*MsgCreateAuthenticatedAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuthenticatedAccount not implemented")
}
func (*UnimplementedMsgServer) UpdateCredentials(ctx context.Context, req *MsgUpdateCredentials) (*MsgUpdateCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCredentials not implemented")
}
func (*UnimplementedMsgServer) DeleteCredentials(ctx context.Context, req *MsgDeleteCredentials) (*MsgDeleteCredentials, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCredentials not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateAuthenticatedAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateAuthenticatedAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateAuthenticatedAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.authn.Msg/CreateAuthenticatedAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateAuthenticatedAccount(ctx, req.(*MsgCreateAuthenticatedAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCredentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.authn.Msg/UpdateCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCredentials(ctx, req.(*MsgUpdateCredentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteCredentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.authn.Msg/DeleteCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteCredentials(ctx, req.(*MsgDeleteCredentials))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.authn.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuthenticatedAccount",
			Handler:    _Msg_CreateAuthenticatedAccount_Handler,
		},
		{
			MethodName: "UpdateCredentials",
			Handler:    _Msg_UpdateCredentials_Handler,
		},
		{
			MethodName: "DeleteCredentials",
			Handler:    _Msg_DeleteCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/authn/tx.proto",
}

func (m *MsgCreateAuthenticatedAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAuthenticatedAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAuthenticatedAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeployMsg != nil {
		{
			size, err := m.DeployMsg.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Credential) > 0 {
		i -= len(m.Credential)
		copy(dAtA[i:], m.Credential)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Credential)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateAuthenticatedAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAuthenticatedAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAuthenticatedAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCredentials) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCredentials) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCredentials) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewAuthn) > 0 {
		i -= len(m.NewAuthn)
		copy(dAtA[i:], m.NewAuthn)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewAuthn)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Kind) > 0 {
		i -= len(m.Kind)
		copy(dAtA[i:], m.Kind)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Kind)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCredentialsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCredentialsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCredentialsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteCredentials) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteCredentials) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteCredentials) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteCredentialsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteCredentialsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteCredentialsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateAuthenticatedAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Credential)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DeployMsg != nil {
		l = m.DeployMsg.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateAuthenticatedAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateCredentials) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Kind)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewAuthn)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateCredentialsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteCredentials) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteCredentialsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateAuthenticatedAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAuthenticatedAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAuthenticatedAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credential", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Credential = append(m.Credential[:0], dAtA[iNdEx:postIndex]...)
			if m.Credential == nil {
				m.Credential = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeployMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeployMsg == nil {
				m.DeployMsg = &types.MsgDeploy{}
			}
			if err := m.DeployMsg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateAuthenticatedAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAuthenticatedAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAuthenticatedAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCredentials) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCredentials: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCredentials: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kind = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewAuthn", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewAuthn = append(m.NewAuthn[:0], dAtA[iNdEx:postIndex]...)
			if m.NewAuthn == nil {
				m.NewAuthn = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCredentialsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCredentialsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCredentialsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteCredentials) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteCredentials: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteCredentials: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteCredentialsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteCredentialsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteCredentialsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
